- v3.0.*/firestore/android.md
Just fixed what looked like a copy and paste from the Admob module section.  Also, it looks like 'dependency' is misspelled as 'dependancy' in all of the module Android installation sections.
> Fix 'Admob' to 'Firestore' and typo

- v3.0.*/core/default-app.md
- v3.0.*/migration-guide.md
- v3.0.*/release-notes.md
* If `setPersistenceEnabled` is in `MainActivity`, it can raise a error such as `Calls to setPersistenceEnabled() must be made before any other usage of FirebaseDatabase instance`.
* https://stackoverflow.com/questions/37753991/com-google-firebase-database-databaseexception-calls-to-setpersistenceenabled/37766261#37766261
> Fix location of setPersistenceEnabled in Android

- v3.1.*/config/reference/config.md
@Ehesp Noticed the `/` was missing from the closing `[/collapse]` tags which causes the collapse example functionality to break in the firebase config examples. Added those in now.
> Adds missing forward slash in closing collapse tag

- v3.1.*/analytics/ios.md
[Firebase doc](https://firebase.google.com/docs/analytics/ios/start) mentions that only `pod 'Firebase/Core'` is required to analytics.
> Analytics Pod doesn't need to be included

- v3.1.*/installation/ios.md
Fixes: https://github.com/invertase/react-native-firebase/issues/624
Modify recommended position to add [FIRApp configure]; early in the `didFinishLaunchingWithOptions:(NSDictionary *)launchOptions` method before creating the RCTRootView.
Otherwise the initialization can happen too late after already being needed in the JavaScript code.
> iOS Init: Modify recommended position to add [FIRApp configure];

- v3.1.*/auth/social-auth.md
While implementing social login, I noticed that I couldn't simply drag and drop for the expected functionality to work. After implementing it in my project, these functions should work automatically for users who want to get started right away. (For instance, I had to call `.configure()` before being able to use the google auth, which I didn't know from using the given example.)
> Make social login instructions easier to use

- docs/installation/ios.md
The docs do mention needing to run `pod update` to get the latest versions, but I got tripped up because that note comes before the step where you add your project's pods to the Podfile. I saw a couple of issues logged related to the error I encountered about the `RNFirebase` module, so I've commented on those directly, but hopefully adding a specific troubleshooting step helps others avoid the problem some of us have run in to.
> Add a troubleshooting step for outdated pods

- docs/firestore/reference/DocumentSnapshot.md
The documentation for the `id` field had a copy-paste mistake from the `exists` field documentation. This mistake is now fixed.
> One-line documentation fix

- docs/auth/phone-auth.md
`if (!!message.length) return null;`
is always true if there is a message, returning null will swallow the message.
> problem with phone auth full example

- docs/links/ios.md
If you scroll to the very bottom of https://rnfirebase.io/docs/v3.3.x/links/ios you'll see that code formatting is off
> Fix code formatting in iOS linking docs

- docs/links/android.md
As mentioned in react-native linking docs: https://facebook.github.io/react-native/docs/linking.html#docsNav and in one of the issues I experienced recently https://github.com/invertase/react-native-firebase/issues/826
Android opens new intents when app is opened via dynamic link and breaks whole flow, its fixable by adding  `launchMode="singleTask"` to manifest.
> add launchMode="singleTask" mention to android links doc

- docs/messaging/reference/messaging.md
Let's remove a repeated paragraph on the iOS Only section, very simple change.
> Removing repeated paragraph

- docs/notifications/ios.md
Following the steps described in this docs, the build failed because the `RNFirebaseMessaging` was not defined.
I'm proposing this simple change in the text to make it more clear.
Thank you guys for the amazing job with this library. =)
> Update missing information to documentation

- docs/troubleshooting/ios.md
There's only a small line in the ios installation instructions about ensuring the GoogleService-Info.plist is registered with Xcode, but it is not elaborated on. If I would have had the following instructions it would have saved me a lot of time.
> Adds troubleshoot step for ios

- docs/admob/reference/Interstitial.md
Hey,
Here is just a little typo fix for the `on` method.
By the way, I was wondering why there is nothing on [the reference page](https://rnfirebase.io/docs/v3.3.x/admob/reference/admob) ? There should be #EventTypes and other references, right ?
> Fix wrong method name in Admob Interstitial docs

- docs/release-notes.md
Previously, the Notifications installation instructions for Android was the same as the link for Messaging, updated Readme.MD to route to the proper Notification installation link
> Update link to Android installation instructions

- docs/crashlytics/android.md
Looks like this was updated in the `_config.yaml` to be `tools` instead of `gradle`. Updating so version is included.
> Update fabric version

- docs/installation/android.md
This was causing some confusion in the docs as to which version I should be using now. I'm assuming this is correct, yea?
> Change android version to variable like the rest of docs

- docs/installation/android.md
When proguard's minifyEnabled is set to true you need to tell proguard to keep all RNFirebase classes to be kept as well as not to be logged as a warning. Any proguard warning will result in a build failure.
> Include proguard rules in android instructions

- docs/database/reference/Query.md
I've noticed limitToFirst example is the same as isEqual.
> Fixed typo on Query docs

- docs/_config.yaml
The latest version for `com.google.firebase:firebase-perf` as listed on https://firebase.google.com/docs/android/setup is `16.0.0`
> Incorrect version number for Performance Monitoring

- docs/auth/reference/auth.md
Based on [official Firebase documentation](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#createUserAndRetrieveDataWithEmailAndPassword), it looks like the original error codes were copied from the signIn...() methods.
> Error codes corrected for createUser...()

- docs/auth/social-auth.md
I noticed that the address is pointing to old repository. Old link still redirects to the new one but it's better to use the latest url.
> Update react-native-google-signin Github address

- docs/firestore/android.md
Firestore on Android requires multidex to be enabled so I've updated the documentation to reflect this. 
Without this change the app won't build for Android
> Update Firestore android.md

- docs/auth/ios.md
Without this step, an error will be thrown.
This is just a little configuration as clearly documented in firebase documentation.
> add missing step: Enable app verification

- docs/firestore/reference/FieldValue.md
Docs update for
https://github.com/invertase/react-native-firebase/pull/1624
> docs: FieldValue.arrayRemove, FieldValue.arrayUnion

- docs/storage/reference/Reference.md
putFile method accepts second optional parameters as well. Doc mentions only first one.
> Added putFile method parameter

- docs/analytics/ios.md
Per discussion on https://github.com/invertase/react-native-firebase/issues/2071 - added a note about the cocoapod required for automatic audience metric collection on iOS
This is the PR for v5.x.x
> docs: noted iOS pod needed for iOS audience stats

- docs/_config.yaml
- docs/admob/android.md
- docs/admob/ios.md
- docs/getting-started.md
- docs/installation/initial-setup.md
- docs/perf-mon/android.md
- docs/releases/v5.4.x.md
The big news here is the breaking change notice for the proposed semver policy change to allow breaks in v5 minor. I explain the reasoning and I've proposed it in a few places with no dissent as yet.
My idea is to get a v5.4.x patch release in shape and release it with some sort of CLI messaging as well (a postinstall echo or however you do it), then commence with v5.5 to get PRs merged that help track with underlying SDKs.
I will try to bridge between v5 and v6 by verifying any underlying SDK tracking work is reflected in v6 as well so straddling the branches is not onerous.
there were some special notes for the perf plugin and admob as the
versions moved
also config.yml::ios|android.fabric.version was unused (grep verified) and lagged the crashlytics version, removed
> docs: notice semver policy change, update dep versions, fill changelog

- docs/auth/reference/UserMetadata.md
For the 5.x Auth version now, I noticed the User.UserMetadata times were coming back as standard Date milliseconds values, and thought the documentation should match
> docs: Update User.UserMetadata timestamp formats to match plugin return vals

- docs/admob/android.md
Android 9.0 removed by default all traces of the old Apache HTTP library. However, it seems that some libraries need it. You need to add this to your manifest inside the element to enable legacy HTTP Library.
> docs: Firebase Admob requires AdMob ID, and legacy http workaround

- docs/notifications/android-actions.md
Just found a typo.
In all the file, `react-native-firebase` is imported as `firebase` but for, for remote input, it's imported as `RNfirebase`
> docs: fix typo on notifications for android actions

- docs/firestore/reference/Settings.md
The cacheSizeBytes property documentation is now added in the Settings section of the firestore reference.
> docs: add document section for firestore.settings.cacheSizeBytes

- docs/releases/v5.4.x.md
Sorry for being change-y on the whitespace in this file, I delinted it at the same time. If you look at it with no whitespace it's clean.
This is I think the full list of changes merged in since 5.4.2, formatted I hope correctly, and I hope easy and ready to go
I think everything is in shape for a 5.4.3 release after the breaking change notice on npm install is approved-by-not-me-the-author and merged-by-anyone: https://github.com/invertase/react-native-firebase/pull/2214
> Prepare for 5.4.3 release

- docs/releases/v5.4.x.md
I had an incorrect PR URL for the AdMob fix
but more importantly something is terribly wrong with the formatting on the published release notes and I'm not sure what as it previews correctly in VSCode
I made some changes I think will fix it as it renders on rnfirebase.io but the goal here is for this page to look normal: https://rnfirebase.io/docs/v5.x.x/releases/v5.4.x
If you could approve and merge it then look at the actual page - if it doesn't look right then I don't know how to fix it as the markdown rendering is different than I'm expecting, and I'll need help
> fix formatting on 5.4.x release notes

- docs/_config.yaml
- docs/invites/android.md
- docs/invites/ios.md
- docs/invites/reference/AndroidInvitation.md
- docs/invites/reference/Invitation.md
- docs/invites/reference/InvitationOpen.md
- docs/invites/reference/Invites.md
- docs/links/reference/DynamicLink.md
- docs/release-notes.md
- docs/releases/v5.5.x.md
This updates the documentation to match https://github.com/invertase/react-native-firebase/pull/2240
> V5 Firebase SDK update

- docs/getting-started.md
- docs/releases/v5.5.x.md
I'll push a release notes page without a formatting error one of these days.
Until then, this should fix the v5.5.x page
This also adds the point releases from overnight and this morning, and updates the compatibility chart
> fix formatting, add v5.5.x compatibility matrix, document patch releases

- docs/messaging/receiving-messages.md
This link was pointing to the wrong "Android Installation" page
> Android Messaging - Fix installation link on receiving messages

- docs/firestore/android.md
This is to align the docs with Starter kit: https://github.com/invertase/react-native-firebase-starter/blob/2a76b89a5cd8ed4b7e7af9a9072e9ad79e80c143/android/app/build.gradle#L114. The build does not currently work without this.
> Add `multiDexEnabled true` to Android setup

- docs/admob/android.md
- docs/analytics/android.md
- docs/auth/android.md
- docs/config/android.md
- docs/crashlytics/android.md
- docs/database/android.md
- docs/firestore/android.md
- docs/functions/android.md
- docs/iid/android.md
- docs/invites/android.md
- docs/links/android.md
- docs/messaging/android.md
- docs/notifications/android.md
- docs/perf-mon/android.md
- docs/storage/android.md
The getPackages method has changed with the latest version of React Native to not include the default firebase package and requires a different way of adding module packages. This updates the documentation for Auth to reflect this. If this PR is approved, I can make this same change across other modules.
> Updates to reflect new React Native MainApplication code

- docs/_config.yaml
- docs/links/android.md
Per title: the docs currently mistakenly omit `com.google.firebase:firebase-invites`: this adds it in
Issue: https://github.com/invertase/react-native-firebase/issues/2528
> Update docs for Android dynamic links: still need invites

- docs/auth/social-auth.md
Clone of https://github.com/invertase/react-native-firebase/pull/2982
> Add apple social auth to docs (courtesy @russellwheatley)

- docs/links/ios.md
In
```
application:(UIApplication *)application openURL:(NSURL *)url  options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
```
we couldn't call method below.
```
[RCTLinkingManager application:application openURL:url sourceApplication:sourceApplication annotation:annotation];
```
And I think that calling below is right.
```
[RCTLinkingManager application:application openURL:url options:options];
```
> Fix ios.md

- docs/notifications/ios.md
I recently fix a bug that was caused by a wrong placement of `[RNFirebaseNotifications configure]`. It was impossible to display notification when the app was in foreground.
One of my team member place it after `RCTRootView`. It took us 6 hours to figure it out.
It is very well specified in the global installation for `[FIRApp configure]`.
I thought it would be a good idea to be more precise here too, even if it is already written just before the code example (but not as visible as for the global installation)
> Add warning about [RNFirebaseNotifications configure] placement.

- docs/installation/android.md
gradle version of 4.4  is not compatible with android build tools 3.4.1
[watch this](https://developer.android.com/studio/releases/gradle-plugin#updating-gradle)
>  update gradle version in android.md

- docs/_config.yaml
I got really stuck trying to use version 5.6.0 on iOS because of the old version in the docs. This fixes that. 
Should close [#2998](https://github.com/invertase/react-native-firebase/issues/2998) in the main repo.
> [Docs] update ios pod versions

- docs/analytics/reference/analytics.md
This PR clarifies the difference between the maximum character lengths supported for event parameter names and event parameter values.
Source: https://support.google.com/firebase/answer/9237506?hl=en
> docs(analytics): max char length for event param name & value
