invertase/react-native-firebase-docs

v3.0.*/config/reference/config.md
`getValue` should be `getValues` in this case.
=> Update documentation for RemoteConfig

v3.1.*/auth/android.md
Documentation accidentally said RNFirebaseAnalyticsPackage instead of RNFirebaseAuthPackage.
=> Correct AnalyticsPackage to AuthPackage

v3.1.*/links/ios.md
Fix wrong argument declaration in Dynamic Links iOS Installation docs
=> Fix Dynamic Links iOS Installation docs

docs/database/android.md
From 'RNFirebaseMessagingPackage' to  'RNFirebaseDatabasePackage'
=> Changed line 16

docs/links/ios.md
I came across situation described in this issue: https://github.com/invertase/react-native-firebase/issues/849 (multiple sources of deep / universal links), and thought it would be a good idea to explain how to handle this in docs for non native developers.
=> Added description about handling multiple universal / deep links

docs/auth/social-auth.md
Replaced deprecated signInWithCredential with signInAndRetrieveDataWithCredential
=> Replace deprecated signInWithCredential

docs/notifications/reference/AndroidNotification.md
The function did not provide enough information of the type of data that needed to be supplied to it, I have added some more information that makes it easier to use.
=> Updated documentation for the setBigPicture function

docs/notifications/reference/Notifications.md
Added an example for `onNotificationOpened` usage for more clarity.
=> Added example usage for onNotificationOpened

docs/invites/android.md
RNFirebaseInvitesPackage is part of the `invites` namespace
=> Corrected import statement

docs/messaging/introduction.md
Clarify that data messages cannot be sent from the Firebase console - I spent too much time on this :)
=> Clarification

docs/auth/social-auth.md
=> Forgotten import

docs/auth/reference/User.md
=> Update User.md formatting

docs/firestore/android.md
Added filename to "Enable multidex" section
=> Update Firestore android.md

docs/invites/reference/Invites.md, docs/links/android.md, docs/links/ios.md, docs/links/reference/links.md
https://firebase.google.com/docs/dynamic-links/ios/receive#open-dynamic-links-in-your-app
=> update docs to use Firebases new dynamic link url

docs/_sidebar.yaml, docs/messaging/reference/IOSMessaging.md, docs/messaging/reference/IOSMessanging.md, docs/messaging/reference/Messaging.md
Doucument for invertase/react-native-firebase#1626
https://rnfirebase.io/docs/ios-messanging/messaging/reference/IOSMessaging
=> Add IOSMessaging module

docs/_sidebar.yaml, docs/crashlytics/manual-initialization.md, docs/crashlytics/reference/crashlytics.md
Pull request invertase/react-native-firebase#1718
=> Add manually enableCrashlyticsCollection docs

docs/installation/initial-setup.md
Found a typo while reading the doc
=> Fix typo on initial-setup.md

docs/_config.yaml, docs/getting-started.md, docs/messaging/android.md
https://github.com/invertase/react-native-firebase/pull/1805
Merge on v5.2.0 release.
=> Docs -> v5.2.0

docs/auth/reference/auth.md
Removed old two which are incorrect. Added 5 error codes in Firebase JS Doc
=> Correct error codes for verifyPhoneNumber function

docs/auth/social-auth.md
I've tested this with both iOS and Android and it worked. Let me know if there's anything that should be changed
🔥
=> Update Social Media Auth page with Twitter Signin

docs/admob/reference/admob.md, docs/auth/reference/AuthSettings.md, docs/contributing.md, docs/releases/v5.0.0.md, docs/testing.md
Not all URLs were changed, but those that were making it difficult to read the document was changed.
=> Fixed URL Banch v5.x.x

docs/notifications/receiving-notifications.md
=> missing comma

docs/crashlytics/reference/crashlytics.md
Documentation contribution for PR#1940.
https://github.com/invertase/react-native-firebase/pull/1940
:fire:
=> [Crashlytics] V5.x.x New Methods

docs/installation/ios.md
Following https://github.com/invertase/react-native-firebase/pull/2328
=> [5.x.x] Update iOS installation guide for cocoapods with use_frameworks!

docs/getting-started.md
Hello!
I'm not sure that this is the best place to mention that, but I'm sure it will help people 
See https://github.com/invertase/react-native-firebase/issues/2409
=> Add iOS 13 crash warning to getting started page

docs/getting-started.md, docs/release-notes.md, docs/releases/v5.6.0.md
Here are the release notes for v5.6.0 - it's headed out the door right now :muscle:
=> Add release notes for v5.6.0

docs/crashlytics/ios.md
docs for https://github.com/invertase/react-native-firebase/pull/2260
=> Add instructions how to integrate with subspecs

docs/installation/ios.md
See https://github.com/invertase/react-native-firebase/issues/2409#issuecomment-575573307
=> Add Firebase iOS SDK version ^6.5.x warning
